### ISSUE TITLE
Rename all `D` to `γ` in docstrings and docpages

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DelayEmbeddings.jl#2]
Through experience we have realized that one cannot longer call the `D` parameter "embedding dimension" but only the "number of temporal neighbors".

That is because `D` doesn't always directly correspond to the resulting dimension. For example, if one does multiple timeseries embedding (which we have support for) then `D` is not the dimension. The same concept expands to TimeseriesPrediction.

After consideration we have decided that `γ` is a good name for this parameter, which will stand for the amount of temporal neighbors to be used in the embedding.

**Comment by heliosdrm** [comment]
I understand the argument, although on the other hand the concept of "embedding dimensions" is largely used in the literature, so it is at least necessary to document clearly the relation between the concepts.

Another potentially confusing issue is that the argument of `reconstruct` tells how many temporal neighbors are *added* to the original data series, but in most software packages for RQA the number of embedding dimensions refer to the size of the reconstructed phase space (following the formulation in most papers and books about the topic).

The worst part of this problem is that it is very likely to pass unnoticed, since in RQA embedding the time series is only an intermediate step. I'm specially concerned about those cases where the number of embedding dimensions is not searched, but fixed by some heuristic or recommendation in the field of research: users may apply it blindly, and then analyze the recurrence plot without ever noticing that the phase space that they have used has one dimension less than what they wanted.

How can we avoid this pitfall? Good documentation is key, but I'm not sure if it will be enough.

**Comment by Datseris** [comment]
Hm you are right, this is a danger one needs to be sure that it doesn't hurt users.

How does this work with multivariate timeseries? Or are the completely unused in the field of RQA?

**Comment by Datseris** [comment]
Another way to go around this is to re-write the code here so that `D` does indeed correspond to the embedding dimension (even though that would be straight-out false in multivariate embeddings) and change the parameter name in TimeseriesPrediction to `γ`. Because there it truly makes no sense to have `D`.

**Comment by Datseris** [comment]
I thought about it more and I think you are over-worrying. First of all, anyone that wants to do embedding **must** read the documentation string, just to deduce which parameter is first: is the function called with `τ, D` or with `D, τ`? In the simplest case both are integers and thus it is not possible to know how to call the function without actually reading the documentation.

Then, in the call signature the user will see no `D`, just `τ, γ` and thus will be forced to read the line "`γ` is the number of temporal neighbors. For univariate timeseries this corresponds to one less than the embedding dimension `D`".

I think we can go ahead with this, let me know if you have more concerns.

**Comment by Datseris** [comment]
@heliosdrm DelayEmbeddings just got registered, so if we want to breaking changes, the sooner the better.

Your opinion here is very important since you are the expert of the field. I am not using RQA in my research so I do not know how impactful this _really_ is. From my perspective this does not really seem like a big deal, but its your call.

**Comment by heliosdrm** [comment]
Your argument is sound, so I think that DelayEmbeddings does not need to be changed. The issue with RQA is that the concept of "embedding dimension" is deeply rooted in the literature -and other software packages follow that convention-, so users coming from other languages (R, Python, Matlab) will have to adapt to the concept of "temporal neighbor".

If `reconstruct` is being used in other packages I don't think that it is worth to break it. But perhaps the function `embed` might be kept specifically for RQA, as a wrapper that calls `reconstruct` with `γ=D-1`, with a deprecation warning that recommends using `reconstruct` instead.

**Comment by Datseris** [comment]
Oh damn! This is such an _amazing_ idea!!! How did I not think about it!

There is no reason to keep `embed` in RQA, we put it here in this repo! Yeeees!!! The perfect solution!

and as you said, embed just does `embed(s, D, τ) = reconstruct(s, D-1, τ)` !!! Nice! :) 

Both will be exported and both will have their respective documentation strings!!!

**Comment by Datseris** [comment]
@heliosdrm I hope this is fine now! Let me know if you want more changes!
