### ISSUE TITLE
Tests with Rössler system failing without relevant changes in code

### ISSUE THREAD

**Issue by heliosdrm** [JuliaDynamics/DelayEmbeddings.jl#20]
78b476d passed the CI tests, and cb5f07c5 (PR #19) fails, although in my local machine it does not. There must be some change in other packages that I have not updated that cause the failure.

**Comment by heliosdrm** [comment]
I just saw that de8c7eb also fails, and that commit only consists of documentation changes since 78b476d, so it is definitely something outside DelayEmbeddings.

**Comment by heliosdrm** [comment]
Found it, it is this: https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/issues/81
Updating `DynamicalSystemsBase` to v1.2.2 in my machine reproduced the CI failure.

So, the tests should be updated to be consistent with the new way of integrating of `DynamicalSystemsBase`, unless such new integration is not wanted and that package reverted to the way it worked in 1.1.

**Comment by Datseris** [comment]
Yeah, we should talk about this. The reason is https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/issues/81#issuecomment-461967069 , i.e. we have changed the default solver.

I was wondering whether I should change it to 2.0, but I read SymVer and it was saying "increment major version when doing a breaking API change". I didn't really know what to do as this is not an API change.
